<header id="qodef-page-header" role="banner">
<div id="qodef-page-header-inner" class>
<nav class="qodef-header-navigation" role="navigation" aria-label="Split Left to Right Menu">
<ul id="menu-main-menu-1" class="menu"><li class="menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor current-menu-parent menu-item-has-children menu-item-19 qodef--hide-link qodef-menu-item--narrow"><a href="<?= urlOf('index.php') ?>"><span class="qodef-menu-item-text">Home<svg class="qodef-svg--menu-arrow qodef-menu-item-arrow" xmlns="http://www.w3.org/2000/svg" width="7.207" height="13.414" viewBox="0 0 7.207 13.414"><path fill="none" stroke="currentColor" stroke-linecap="square" stroke-linejoin="round" d="m.707 12.707 6-6-6-6" /></svg></span></a>
<div class="qodef-drop-down-second"><div class="qodef-drop-down-second-inner">
</li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-4506 qodef--hide-link qodef-menu-item--wide"><a href="<?= urlOf('pages/products.php') ?>"><span class="qodef-menu-item-text">Product<svg class="qodef-svg--menu-arrow qodef-menu-item-arrow" xmlns="http://www.w3.org/2000/svg" width="7.207" height="13.414" viewBox="0 0 7.207 13.414"><path fill="none" stroke="currentColor" stroke-linecap="square" stroke-linejoin="round" d="m.707 12.707 6-6-6-6" /></svg></span></a>
</li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-20 qodef--hide-link qodef-menu-item--narrow"><a href="<?= urlOf('pages/about.php') ?>" onclick="JavaScript: return false;"><span class="qodef-menu-item-text">About<svg class="qodef-svg--menu-arrow qodef-menu-item-arrow" xmlns="http://www.w3.org/2000/svg" width="7.207" height="13.414" viewBox="0 0 7.207 13.414"><path fill="none" stroke="currentColor" stroke-linecap="square" stroke-linejoin="round" d="m.707 12.707 6-6-6-6" /></svg></span></a>
<div class="qodef-drop-down-second"><div class="qodef-drop-down-second-inner">
</li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-22 qodef--hide-link qodef-menu-item--narrow"><a href="<?= urlOf('pages/contact.php') ?>" ><span class="qodef-menu-item-text">Contact<svg class="qodef-svg--menu-arrow qodef-menu-item-arrow" xmlns="http://www.w3.org/2000/svg" width="7.207" height="13.414" viewBox="0 0 7.207 13.414"><path fill="none" stroke="currentColor" stroke-linecap="square" stroke-linejoin="round" d="m.707 12.707 6-6-6-6" /></svg></span></a>
<div class="qodef-drop-down-second"><div class="qodef-drop-down-second-inner">
</li>
</ul> </nav>
<a itemprop="url" class="qodef-header-logo-link qodef-height--not-set qodef-source--image" href="<?= urlOf('index.php') ?>" rel="home">
<img width="376" height="124" src="https://fidalgo.qodeinteractive.com/wp-content/uploads/2023/09/logo-main.png" class="qodef-header-logo-image qodef--main" alt="logo main" itemprop="image" srcset="https://fidalgo.qodeinteractive.com/wp-content/uploads/2023/09/logo-main.png 376w, https://fidalgo.qodeinteractive.com/wp-content/uploads/2023/09/logo-main-300x99.png 300w" sizes="(max-width: 376px) 100vw, 376px" /><img width="376" height="124" src="https://fidalgo.qodeinteractive.com/wp-content/uploads/2023/09/logo-main.png" class="qodef-header-logo-image qodef--dark" alt="logo dark" itemprop="image" srcset="https://fidalgo.qodeinteractive.com/wp-content/uploads/2023/09/logo-main.png 376w, https://fidalgo.qodeinteractive.com/wp-content/uploads/2023/09/logo-main-300x99.png 300w" sizes="(max-width: 376px) 100vw, 376px" /><img width="376" height="124" src="https://fidalgo.qodeinteractive.com/wp-content/uploads/2023/09/logo-main.png" class="qodef-header-logo-image qodef--light" alt="logo light" itemprop="image" srcset="https://fidalgo.qodeinteractive.com/wp-content/uploads/2023/09/logo-main.png 376w, https://fidalgo.qodeinteractive.com/wp-content/uploads/2023/09/logo-main-300x99.png 300w" sizes="(max-width: 376px) 100vw, 376px" /></a>
<div class="qodef-widget-holder qodef--one">
<div id="fidalgo_core_button-3" class="widget widget_fidalgo_core_button qodef-header-widget-area-one" data-area="header-widget-one"><a class="qodef-shortcode qodef-m  qodef-button qodef-layout--outlined  qodef-html--link" href="https://fidalgo.qodeinteractive.com/book-a-table/" target="_self"> <span class="qodef-m-text">Book a table</span></a></div> </div>
</div>
<div class="qodef-header-sticky qodef-skin--viridian-green qodef-appearance--up">
<div class="qodef-header-sticky-inner">
<nav class="qodef-header-navigation" role="navigation" aria-label="Split Left to Right Menu">
<ul id="menu-main-menu-2" class="menu"><li class="menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor current-menu-parent menu-item-has-children menu-item-19 qodef--hide-link qodef-menu-item--narrow"><a href="#" onclick="JavaScript: return false;"><span class="qodef-menu-item-text">Home<svg class="qodef-svg--menu-arrow qodef-menu-item-arrow" xmlns="http://www.w3.org/2000/svg" width="7.207" height="13.414" viewBox="0 0 7.207 13.414"><path fill="none" stroke="currentColor" stroke-linecap="square" stroke-linejoin="round" d="m.707 12.707 6-6-6-6" /></svg></span></a>
<div class="qodef-drop-down-second"><div class="qodef-drop-down-second-inner"><ul class="sub-menu">
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-home current-menu-item page_item page-item-24 current_page_item menu-item-461"><a href="https://fidalgo.qodeinteractive.com/"><span class="qodef-menu-item-text">Main Home</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1405"><a href="https://fidalgo.qodeinteractive.com/sushi-restaurant/"><span class="qodef-menu-item-text">Sushi Restaurant</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-4520"><a href="https://fidalgo.qodeinteractive.com/nightclub-home/"><span class="qodef-menu-item-text">Nightclub Home</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-4522"><a href="https://fidalgo.qodeinteractive.com/fine-dining-home/"><span class="qodef-menu-item-text">Fine Dining Home</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1406"><a href="https://fidalgo.qodeinteractive.com/cocktail-bar/"><span class="qodef-menu-item-text">Cocktail Bar</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-4519"><a href="https://fidalgo.qodeinteractive.com/mediterranean-cafe/"><span class="qodef-menu-item-text">Mediterranean Café</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-7931"><a href="https://fidalgo.qodeinteractive.com/pizzeria-home/"><span class="qodef-menu-item-text">Pizzeria Home</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-4521"><a href="https://fidalgo.qodeinteractive.com/bar-home/"><span class="qodef-menu-item-text">Bar Home</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1407"><a href="https://fidalgo.qodeinteractive.com/patisserie-home/"><span class="qodef-menu-item-text">Pâtisserie Home</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-4518"><a href="https://fidalgo.qodeinteractive.com/steak-house/"><span class="qodef-menu-item-text">Steak House</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-10404"><a href="https://fidalgo.qodeinteractive.com/seafood-restaurant/"><span class="qodef-menu-item-text">Seafood Restaurant</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-6356"><a href="https://fidalgo.qodeinteractive.com/bistro-home/"><span class="qodef-menu-item-text">Bistro Home</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-6357"><a href="https://fidalgo.qodeinteractive.com/cafe-home/"><span class="qodef-menu-item-text">Café Home</span></a></li>
</ul></div></div>
</li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-4506 qodef--hide-link qodef-menu-item--wide"><a href="#" onclick="JavaScript: return false;"><span class="qodef-menu-item-text">Menu<svg class="qodef-svg--menu-arrow qodef-menu-item-arrow" xmlns="http://www.w3.org/2000/svg" width="7.207" height="13.414" viewBox="0 0 7.207 13.414"><path fill="none" stroke="currentColor" stroke-linecap="square" stroke-linejoin="round" d="m.707 12.707 6-6-6-6" /></svg></span></a>
<div class="qodef-drop-down-second"><div class="qodef-drop-down-second-inner qodef-content-grid"><ul class="sub-menu">
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-4517"><div class="qodef-mega-menu-widget-holder"><div class="widget widget_fidalgo_core_image_with_text" data-area="wide-menu"><div class="qodef-shortcode qodef-m  qodef-image-with-text qodef-layout--text-below qodef-align--left   "> <div class="qodef-m-image"> <a itemprop="url" href="https://fidalgo.qodeinteractive.com/menu-vertical/" target="_self"> <img width="333" height="333" src="https://fidalgo.qodeinteractive.com/wp-content/uploads/2024/03/dd-menu-img1.jpg" class="attachment-full size-full" alt="a" decoding="async" srcset="https://fidalgo.qodeinteractive.com/wp-content/uploads/2024/03/dd-menu-img1.jpg 333w, https://fidalgo.qodeinteractive.com/wp-content/uploads/2024/03/dd-menu-img1-300x300.jpg 300w, https://fidalgo.qodeinteractive.com/wp-content/uploads/2024/03/dd-menu-img1-150x150.jpg 150w, https://fidalgo.qodeinteractive.com/wp-content/uploads/2024/03/dd-menu-img1-100x100.jpg 100w" sizes="(max-width: 333px) 100vw, 333px" /> </a> </div> <div class="qodef-m-content"> <h6 class="qodef-m-title" style="margin-top: 15px"> <a itemprop="url" href="https://fidalgo.qodeinteractive.com/menu-vertical/" target="_self"> menu vertical </a> </h6> </div></div></div></div></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-4515"><div class="qodef-mega-menu-widget-holder"><div class="widget widget_fidalgo_core_image_with_text" data-area="wide-menu2"><div class="qodef-shortcode qodef-m  qodef-image-with-text qodef-layout--text-below qodef-align--left   "> <div class="qodef-m-image"> <a itemprop="url" href="https://fidalgo.qodeinteractive.com/menu-small-images/" target="_self"> <img width="333" height="333" src="https://fidalgo.qodeinteractive.com/wp-content/uploads/2024/03/dd-menu-img3.jpg" class="attachment-full size-full" alt="a" decoding="async" srcset="https://fidalgo.qodeinteractive.com/wp-content/uploads/2024/03/dd-menu-img3.jpg 333w, https://fidalgo.qodeinteractive.com/wp-content/uploads/2024/03/dd-menu-img3-300x300.jpg 300w, https://fidalgo.qodeinteractive.com/wp-content/uploads/2024/03/dd-menu-img3-150x150.jpg 150w, https://fidalgo.qodeinteractive.com/wp-content/uploads/2024/03/dd-menu-img3-100x100.jpg 100w" sizes="(max-width: 333px) 100vw, 333px" /> </a> </div> <div class="qodef-m-content"> <h6 class="qodef-m-title" style="margin-top: 15px"> <a itemprop="url" href="https://fidalgo.qodeinteractive.com/menu-small-images/" target="_self"> menu small images </a> </h6> </div></div></div></div></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-4514"><div class="qodef-mega-menu-widget-holder"><div class="widget widget_fidalgo_core_image_with_text" data-area="wide-menu3"><div class="qodef-shortcode qodef-m  qodef-image-with-text qodef-layout--text-below qodef-align--left   "> <div class="qodef-m-image"> <a itemprop="url" href="https://fidalgo.qodeinteractive.com/menu-big-images/" target="_self"> <img width="333" height="333" src="https://fidalgo.qodeinteractive.com/wp-content/uploads/2024/03/dd-menu-img5.jpg" class="attachment-full size-full" alt="a" decoding="async" srcset="https://fidalgo.qodeinteractive.com/wp-content/uploads/2024/03/dd-menu-img5.jpg 333w, https://fidalgo.qodeinteractive.com/wp-content/uploads/2024/03/dd-menu-img5-300x300.jpg 300w, https://fidalgo.qodeinteractive.com/wp-content/uploads/2024/03/dd-menu-img5-150x150.jpg 150w, https://fidalgo.qodeinteractive.com/wp-content/uploads/2024/03/dd-menu-img5-100x100.jpg 100w" sizes="(max-width: 333px) 100vw, 333px" /> </a> </div> <div class="qodef-m-content"> <h6 class="qodef-m-title" style="margin-top: 15px"> <a itemprop="url" href="https://fidalgo.qodeinteractive.com/menu-big-images/" target="_self"> menu big images </a> </h6> </div></div></div></div></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-4516"><div class="qodef-mega-menu-widget-holder"><div class="widget widget_fidalgo_core_image_with_text" data-area="wide-menu4"><div class="qodef-shortcode qodef-m  qodef-image-with-text qodef-layout--text-below qodef-align--left   "> <div class="qodef-m-image"> <a itemprop="url" href="https://fidalgo.qodeinteractive.com/menu-simple/" target="_self"> <img width="333" height="333" src="https://fidalgo.qodeinteractive.com/wp-content/uploads/2024/03/dd-menu-img4.jpg" class="attachment-full size-full" alt="a" decoding="async" srcset="https://fidalgo.qodeinteractive.com/wp-content/uploads/2024/03/dd-menu-img4.jpg 333w, https://fidalgo.qodeinteractive.com/wp-content/uploads/2024/03/dd-menu-img4-300x300.jpg 300w, https://fidalgo.qodeinteractive.com/wp-content/uploads/2024/03/dd-menu-img4-150x150.jpg 150w, https://fidalgo.qodeinteractive.com/wp-content/uploads/2024/03/dd-menu-img4-100x100.jpg 100w" sizes="(max-width: 333px) 100vw, 333px" /> </a> </div> <div class="qodef-m-content"> <h6 class="qodef-m-title" style="margin-top: 15px"> <a itemprop="url" href="https://fidalgo.qodeinteractive.com/menu-simple/" target="_self"> menu simple </a> </h6> </div></div></div></div></li>
</ul></div></div>
</li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-20 qodef--hide-link qodef-menu-item--narrow"><a href="#" onclick="JavaScript: return false;"><span class="qodef-menu-item-text">Pages<svg class="qodef-svg--menu-arrow qodef-menu-item-arrow" xmlns="http://www.w3.org/2000/svg" width="7.207" height="13.414" viewBox="0 0 7.207 13.414"><path fill="none" stroke="currentColor" stroke-linecap="square" stroke-linejoin="round" d="m.707 12.707 6-6-6-6" /></svg></span></a>
<div class="qodef-drop-down-second"><div class="qodef-drop-down-second-inner"><ul class="sub-menu">
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5020"><a href="https://fidalgo.qodeinteractive.com/about-us/"><span class="qodef-menu-item-text">About Us</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5019"><a href="https://fidalgo.qodeinteractive.com/meet-the-chef/"><span class="qodef-menu-item-text">Meet The Chef</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5018"><a href="https://fidalgo.qodeinteractive.com/our-team/"><span class="qodef-menu-item-text">Our Team</span></a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-5240 qodef--hide-link"><a href="#" onclick="JavaScript: return false;"><span class="qodef-menu-item-text">Gallery<svg class="qodef-svg--menu-arrow qodef-menu-item-arrow" xmlns="http://www.w3.org/2000/svg" width="7.207" height="13.414" viewBox="0 0 7.207 13.414"><path fill="none" stroke="currentColor" stroke-linecap="square" stroke-linejoin="round" d="m.707 12.707 6-6-6-6" /></svg></span></a>
<ul class="sub-menu">
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5239"><a href="https://fidalgo.qodeinteractive.com/gallery-main/"><span class="qodef-menu-item-text">Gallery Main</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5238"><a href="https://fidalgo.qodeinteractive.com/gallery-standard/"><span class="qodef-menu-item-text">Gallery Standard</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5236"><a href="https://fidalgo.qodeinteractive.com/gallery-masonry/"><span class="qodef-menu-item-text">Gallery Masonry</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5237"><a href="https://fidalgo.qodeinteractive.com/gallery-slider/"><span class="qodef-menu-item-text">Gallery Slider</span></a></li>
</ul>
</li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-21 qodef--hide-link"><a href="#" onclick="JavaScript: return false;"><span class="qodef-menu-item-text">Blog List<svg class="qodef-svg--menu-arrow qodef-menu-item-arrow" xmlns="http://www.w3.org/2000/svg" width="7.207" height="13.414" viewBox="0 0 7.207 13.414"><path fill="none" stroke="currentColor" stroke-linecap="square" stroke-linejoin="round" d="m.707 12.707 6-6-6-6" /></svg></span></a>
<ul class="sub-menu">
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-4504"><a href="https://fidalgo.qodeinteractive.com/blog-right-sidebar/"><span class="qodef-menu-item-text">Right Sidebar</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-7073"><a href="https://fidalgo.qodeinteractive.com/blog-left-sidebar/"><span class="qodef-menu-item-text">Left Sidebar</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-7074"><a href="https://fidalgo.qodeinteractive.com/blog-no-sidebar/"><span class="qodef-menu-item-text">No Sidebar</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-7072"><a href="https://fidalgo.qodeinteractive.com/blog-masonry/"><span class="qodef-menu-item-text">Masonry</span></a></li>
</ul>
</li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-4505 qodef--hide-link"><a href="#" onclick="JavaScript: return false;"><span class="qodef-menu-item-text">Post Formats<svg class="qodef-svg--menu-arrow qodef-menu-item-arrow" xmlns="http://www.w3.org/2000/svg" width="7.207" height="13.414" viewBox="0 0 7.207 13.414"><path fill="none" stroke="currentColor" stroke-linecap="square" stroke-linejoin="round" d="m.707 12.707 6-6-6-6" /></svg></span></a>
<ul class="sub-menu">
<li class="menu-item menu-item-type-post_type menu-item-object-post menu-item-4510"><a href="https://fidalgo.qodeinteractive.com/restaurants-are-changing-the-foods-landscape-and-its-fun/"><span class="qodef-menu-item-text">Standard Post</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-post menu-item-4509"><a href="https://fidalgo.qodeinteractive.com/the-restaurant-review-letter/"><span class="qodef-menu-item-text">Gallery Post</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-post menu-item-4513"><a href="https://fidalgo.qodeinteractive.com/some-fresh-recipes/"><span class="qodef-menu-item-text">Quote Post</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-post menu-item-4511"><a href="https://fidalgo.qodeinteractive.com/creating-the-ideal-restaurant-ambiance/"><span class="qodef-menu-item-text">Link Post</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-post menu-item-4512"><a href="https://fidalgo.qodeinteractive.com/when-restaurant-menu-design-can-help-lower-food-cost/"><span class="qodef-menu-item-text">Audio Post</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-post menu-item-4508"><a href="https://fidalgo.qodeinteractive.com/group-dining-decision/"><span class="qodef-menu-item-text">Video Post</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-post menu-item-4507"><a href="https://fidalgo.qodeinteractive.com/delicious-comfort-food-recipes-that-you-must-try/"><span class="qodef-menu-item-text">No Sidebar Post</span></a></li>
</ul>
</li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5017"><a href="https://fidalgo.qodeinteractive.com/book-a-table/"><span class="qodef-menu-item-text">Book A Table</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5016"><a href="https://fidalgo.qodeinteractive.com/reservations/"><span class="qodef-menu-item-text">Reservations</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5015"><a href="https://fidalgo.qodeinteractive.com/contact-us/"><span class="qodef-menu-item-text">Contact Us</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-7063"><a href="https://fidalgo.qodeinteractive.com/coming-soon/"><span class="qodef-menu-item-text">Coming Soon</span></a></li>
</ul></div></div>
</li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-22 qodef--hide-link qodef-menu-item--narrow"><a href="#" onclick="JavaScript: return false;"><span class="qodef-menu-item-text">Shop<svg class="qodef-svg--menu-arrow qodef-menu-item-arrow" xmlns="http://www.w3.org/2000/svg" width="7.207" height="13.414" viewBox="0 0 7.207 13.414"><path fill="none" stroke="currentColor" stroke-linecap="square" stroke-linejoin="round" d="m.707 12.707 6-6-6-6" /></svg></span></a>
<div class="qodef-drop-down-second"><div class="qodef-drop-down-second-inner"><ul class="sub-menu">
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-465"><a href="https://fidalgo.qodeinteractive.com/shop/"><span class="qodef-menu-item-text">Product List</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-product menu-item-467"><a href="https://fidalgo.qodeinteractive.com/product/pecan-sandies/"><span class="qodef-menu-item-text">Product Single</span></a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-466"><a href="#"><span class="qodef-menu-item-text">Shop Pages<svg class="qodef-svg--menu-arrow qodef-menu-item-arrow" xmlns="http://www.w3.org/2000/svg" width="7.207" height="13.414" viewBox="0 0 7.207 13.414"><path fill="none" stroke="currentColor" stroke-linecap="square" stroke-linejoin="round" d="m.707 12.707 6-6-6-6" /></svg></span></a>
<ul class="sub-menu">
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-464"><a href="https://fidalgo.qodeinteractive.com/my-account/"><span class="qodef-menu-item-text">My Account</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-462"><a href="https://fidalgo.qodeinteractive.com/cart/"><span class="qodef-menu-item-text">Cart</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-463"><a href="https://fidalgo.qodeinteractive.com/checkout/"><span class="qodef-menu-item-text">Checkout</span></a></li>
</ul>
</li>
</ul></div></div>
</li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-8558"><a href="https://fidalgo.qodeinteractive.com/landing/"><span class="qodef-menu-item-text">Landing</span></a></li>
</ul> </nav>
<a itemprop="url" class="qodef-header-logo-link qodef-height--not-set qodef-source--image" href="https://fidalgo.qodeinteractive.com/" rel="home">
<img width="376" height="124" src="https://fidalgo.qodeinteractive.com/wp-content/uploads/2023/09/logo-main.png" class="qodef-header-logo-image qodef--main" alt="logo main" itemprop="image" srcset="https://fidalgo.qodeinteractive.com/wp-content/uploads/2023/09/logo-main.png 376w, https://fidalgo.qodeinteractive.com/wp-content/uploads/2023/09/logo-main-300x99.png 300w" sizes="(max-width: 376px) 100vw, 376px" /></a>
<div class="qodef-widget-holder qodef--one">
<div id="fidalgo_core_button-4" class="widget widget_fidalgo_core_button qodef-sticky-right"><a class="qodef-shortcode qodef-m  qodef-button qodef-layout--outlined  qodef-html--link" href="https://fidalgo.qodeinteractive.com/book-a-table/" target="_self"> <span class="qodef-m-text">book a table</span></a></div> </div>
</div>
</div></header>
<header id="qodef-page-mobile-header" role="banner">
<div id="qodef-page-mobile-header-inner" class>
<a itemprop="url" class="qodef-mobile-header-logo-link qodef-height--set qodef-source--image" href="https://fidalgo.qodeinteractive.com/" rel="home">
<img width="376" height="124" src="https://fidalgo.qodeinteractive.com/wp-content/uploads/2023/09/logo-main.png" class="qodef-header-logo-image qodef--main" alt="logo main" itemprop="image" srcset="https://fidalgo.qodeinteractive.com/wp-content/uploads/2023/09/logo-main.png 376w, https://fidalgo.qodeinteractive.com/wp-content/uploads/2023/09/logo-main-300x99.png 300w" sizes="(max-width: 376px) 100vw, 376px" /></a>
<a href="javascript:void(0)" class="qodef-opener-icon qodef-m qodef-source--predefined qodef-mobile-header-opener">
<span class="qodef-m-icon qodef--open">
<span class="qodef-m-lines"><span class="qodef-m-line qodef--1"></span><span class="qodef-m-line qodef--2"></span><span class="qodef-m-line qodef--3"></span><span class="qodef-m-line qodef--4"></span></span> </span>
<span class="qodef-m-icon qodef--close">
<span class="qodef-m-lines"><span class="qodef-m-line qodef--1"></span><span class="qodef-m-line qodef--2"></span><span class="qodef-m-line qodef--3"></span><span class="qodef-m-line qodef--4"></span></span> </span>
</a>
</div>
<nav class="qodef-mobile-header-navigation" role="navigation" aria-label="Mobile Menu">
<ul id="menu-mob-menu-1" class><li class="menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor current-menu-parent menu-item-has-children menu-item-11152 qodef-menu-item--narrow"><a href="#"><span class="qodef-menu-item-text">Home</span></a><svg class="qodef-svg--menu-arrow qodef-menu-item-arrow" xmlns="http://www.w3.org/2000/svg" width="7.207" height="13.414" viewBox="0 0 7.207 13.414"><path fill="none" stroke="currentColor" stroke-linecap="square" stroke-linejoin="round" d="m.707 12.707 6-6-6-6" /></svg>
<div class="qodef-drop-down-second"><div class="qodef-drop-down-second-inner"><ul class="sub-menu">
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-home current-menu-item page_item page-item-24 current_page_item menu-item-11153"><a href="https://fidalgo.qodeinteractive.com/"><span class="qodef-menu-item-text">Main Home</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-11154"><a href="https://fidalgo.qodeinteractive.com/sushi-restaurant/"><span class="qodef-menu-item-text">Sushi Restaurant</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-11155"><a href="https://fidalgo.qodeinteractive.com/nightclub-home/"><span class="qodef-menu-item-text">Nightclub Home</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-11156"><a href="https://fidalgo.qodeinteractive.com/fine-dining-home/"><span class="qodef-menu-item-text">Fine Dining Home</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-11157"><a href="https://fidalgo.qodeinteractive.com/cocktail-bar/"><span class="qodef-menu-item-text">Cocktail Bar</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-11158"><a href="https://fidalgo.qodeinteractive.com/mediterranean-cafe/"><span class="qodef-menu-item-text">Mediterranean Café</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-11159"><a href="https://fidalgo.qodeinteractive.com/pizzeria-home/"><span class="qodef-menu-item-text">Pizzeria Home</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-11160"><a href="https://fidalgo.qodeinteractive.com/bar-home/"><span class="qodef-menu-item-text">Bar Home</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-11161"><a href="https://fidalgo.qodeinteractive.com/patisserie-home/"><span class="qodef-menu-item-text">Pâtisserie Home</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-11162"><a href="https://fidalgo.qodeinteractive.com/steak-house/"><span class="qodef-menu-item-text">Steak House</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-11163"><a href="https://fidalgo.qodeinteractive.com/seafood-restaurant/"><span class="qodef-menu-item-text">Seafood Restaurant</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-11164"><a href="https://fidalgo.qodeinteractive.com/bistro-home/"><span class="qodef-menu-item-text">Bistro Home</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-11165"><a href="https://fidalgo.qodeinteractive.com/cafe-home/"><span class="qodef-menu-item-text">Café Home</span></a></li>
</ul></div></div>
</li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-11166 qodef-menu-item--narrow"><a href="#"><span class="qodef-menu-item-text">Menu</span></a><svg class="qodef-svg--menu-arrow qodef-menu-item-arrow" xmlns="http://www.w3.org/2000/svg" width="7.207" height="13.414" viewBox="0 0 7.207 13.414"><path fill="none" stroke="currentColor" stroke-linecap="square" stroke-linejoin="round" d="m.707 12.707 6-6-6-6" /></svg>
<div class="qodef-drop-down-second"><div class="qodef-drop-down-second-inner"><ul class="sub-menu">
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-11167"><a href="https://fidalgo.qodeinteractive.com/menu-vertical/"><span class="qodef-menu-item-text">Menu Vertical</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-11168"><a href="https://fidalgo.qodeinteractive.com/menu-simple/"><span class="qodef-menu-item-text">Menu Simple</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-11169"><a href="https://fidalgo.qodeinteractive.com/menu-small-images/"><span class="qodef-menu-item-text">Menu Small Images</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-11170"><a href="https://fidalgo.qodeinteractive.com/menu-big-images/"><span class="qodef-menu-item-text">Menu Big Images</span></a></li>
</ul></div></div>
</li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-11171 qodef-menu-item--narrow"><a href="#"><span class="qodef-menu-item-text">Pages</span></a><svg class="qodef-svg--menu-arrow qodef-menu-item-arrow" xmlns="http://www.w3.org/2000/svg" width="7.207" height="13.414" viewBox="0 0 7.207 13.414"><path fill="none" stroke="currentColor" stroke-linecap="square" stroke-linejoin="round" d="m.707 12.707 6-6-6-6" /></svg>
<div class="qodef-drop-down-second"><div class="qodef-drop-down-second-inner"><ul class="sub-menu">
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-11172"><a href="https://fidalgo.qodeinteractive.com/about-us/"><span class="qodef-menu-item-text">About Us</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-11173"><a href="https://fidalgo.qodeinteractive.com/meet-the-chef/"><span class="qodef-menu-item-text">Meet The Chef</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-11174"><a href="https://fidalgo.qodeinteractive.com/our-team/"><span class="qodef-menu-item-text">Our Team</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-11193"><a href="https://fidalgo.qodeinteractive.com/book-a-table/"><span class="qodef-menu-item-text">Book A Table</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-11194"><a href="https://fidalgo.qodeinteractive.com/reservations/"><span class="qodef-menu-item-text">Reservations</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-11195"><a href="https://fidalgo.qodeinteractive.com/contact-us/"><span class="qodef-menu-item-text">Contact Us</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-11196"><a href="https://fidalgo.qodeinteractive.com/coming-soon/"><span class="qodef-menu-item-text">Coming Soon</span></a></li>
</ul></div></div>
</li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-11175 qodef--hide-link qodef-menu-item--narrow"><a href="#" onclick="JavaScript: return false;"><span class="qodef-menu-item-text">Gallery</span></a><svg class="qodef-svg--menu-arrow qodef-menu-item-arrow" xmlns="http://www.w3.org/2000/svg" width="7.207" height="13.414" viewBox="0 0 7.207 13.414"><path fill="none" stroke="currentColor" stroke-linecap="square" stroke-linejoin="round" d="m.707 12.707 6-6-6-6" /></svg>
<div class="qodef-drop-down-second"><div class="qodef-drop-down-second-inner"><ul class="sub-menu">
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-11176"><a href="https://fidalgo.qodeinteractive.com/gallery-main/"><span class="qodef-menu-item-text">Gallery Main</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-11177"><a href="https://fidalgo.qodeinteractive.com/gallery-standard/"><span class="qodef-menu-item-text">Gallery Standard</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-11178"><a href="https://fidalgo.qodeinteractive.com/gallery-masonry/"><span class="qodef-menu-item-text">Gallery Masonry</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-11179"><a href="https://fidalgo.qodeinteractive.com/gallery-slider/"><span class="qodef-menu-item-text">Gallery Slider</span></a></li>
</ul></div></div>
</li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-11205 qodef--hide-link qodef-menu-item--narrow"><a href="#" onclick="JavaScript: return false;"><span class="qodef-menu-item-text">Blog</span></a><svg class="qodef-svg--menu-arrow qodef-menu-item-arrow" xmlns="http://www.w3.org/2000/svg" width="7.207" height="13.414" viewBox="0 0 7.207 13.414"><path fill="none" stroke="currentColor" stroke-linecap="square" stroke-linejoin="round" d="m.707 12.707 6-6-6-6" /></svg>
<div class="qodef-drop-down-second"><div class="qodef-drop-down-second-inner"><ul class="sub-menu">
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-11180"><a href="#"><span class="qodef-menu-item-text">Blog List</span></a><svg class="qodef-svg--menu-arrow qodef-menu-item-arrow" xmlns="http://www.w3.org/2000/svg" width="7.207" height="13.414" viewBox="0 0 7.207 13.414"><path fill="none" stroke="currentColor" stroke-linecap="square" stroke-linejoin="round" d="m.707 12.707 6-6-6-6" /></svg>
<ul class="sub-menu">
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-11181"><a href="https://fidalgo.qodeinteractive.com/blog-right-sidebar/"><span class="qodef-menu-item-text">Right Sidebar</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-11182"><a href="https://fidalgo.qodeinteractive.com/blog-left-sidebar/"><span class="qodef-menu-item-text">Left Sidebar</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-11183"><a href="https://fidalgo.qodeinteractive.com/blog-no-sidebar/"><span class="qodef-menu-item-text">No Sidebar</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-11184"><a href="https://fidalgo.qodeinteractive.com/blog-masonry/"><span class="qodef-menu-item-text">Masonry</span></a></li>
</ul>
</li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-11185"><a href="#"><span class="qodef-menu-item-text">Post Formats</span></a><svg class="qodef-svg--menu-arrow qodef-menu-item-arrow" xmlns="http://www.w3.org/2000/svg" width="7.207" height="13.414" viewBox="0 0 7.207 13.414"><path fill="none" stroke="currentColor" stroke-linecap="square" stroke-linejoin="round" d="m.707 12.707 6-6-6-6" /></svg>
<ul class="sub-menu">
<li class="menu-item menu-item-type-post_type menu-item-object-post menu-item-11186"><a href="https://fidalgo.qodeinteractive.com/restaurants-are-changing-the-foods-landscape-and-its-fun/"><span class="qodef-menu-item-text">Standard Post</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-post menu-item-11187"><a href="https://fidalgo.qodeinteractive.com/the-restaurant-review-letter/"><span class="qodef-menu-item-text">Gallery Post</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-post menu-item-11188"><a href="https://fidalgo.qodeinteractive.com/some-fresh-recipes/"><span class="qodef-menu-item-text">Quote Post</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-post menu-item-11189"><a href="https://fidalgo.qodeinteractive.com/creating-the-ideal-restaurant-ambiance/"><span class="qodef-menu-item-text">Link Post</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-post menu-item-11190"><a href="https://fidalgo.qodeinteractive.com/when-restaurant-menu-design-can-help-lower-food-cost/"><span class="qodef-menu-item-text">Audio Post</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-post menu-item-11191"><a href="https://fidalgo.qodeinteractive.com/group-dining-decision/"><span class="qodef-menu-item-text">Video Post</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-post menu-item-11192"><a href="https://fidalgo.qodeinteractive.com/delicious-comfort-food-recipes-that-you-must-try/"><span class="qodef-menu-item-text">No Sidebar Post</span></a></li>
</ul>
</li>
</ul></div></div>
</li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-11197 qodef-menu-item--narrow"><a href="#"><span class="qodef-menu-item-text">Shop</span></a><svg class="qodef-svg--menu-arrow qodef-menu-item-arrow" xmlns="http://www.w3.org/2000/svg" width="7.207" height="13.414" viewBox="0 0 7.207 13.414"><path fill="none" stroke="currentColor" stroke-linecap="square" stroke-linejoin="round" d="m.707 12.707 6-6-6-6" /></svg>
<div class="qodef-drop-down-second"><div class="qodef-drop-down-second-inner"><ul class="sub-menu">
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-11198"><a href="https://fidalgo.qodeinteractive.com/shop/"><span class="qodef-menu-item-text">Product List</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-product menu-item-11199"><a href="https://fidalgo.qodeinteractive.com/product/pecan-sandies/"><span class="qodef-menu-item-text">Product Single</span></a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-11200"><a href="#"><span class="qodef-menu-item-text">Shop Pages</span></a><svg class="qodef-svg--menu-arrow qodef-menu-item-arrow" xmlns="http://www.w3.org/2000/svg" width="7.207" height="13.414" viewBox="0 0 7.207 13.414"><path fill="none" stroke="currentColor" stroke-linecap="square" stroke-linejoin="round" d="m.707 12.707 6-6-6-6" /></svg>
<ul class="sub-menu">
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-11201"><a href="https://fidalgo.qodeinteractive.com/my-account/"><span class="qodef-menu-item-text">My Account</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-11202"><a href="https://fidalgo.qodeinteractive.com/cart/"><span class="qodef-menu-item-text">Cart</span></a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-11203"><a href="https://fidalgo.qodeinteractive.com/checkout/"><span class="qodef-menu-item-text">Checkout</span></a></li>
</ul>
</li>
</ul></div></div>
</li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-11204"><a href="https://fidalgo.qodeinteractive.com/landing/"><span class="qodef-menu-item-text">Landing</span></a></li>
</ul> </nav>
</header>